### ISSUE TITLE
Graphical representation of results.

### ISSUE THREAD

**Issue by irfn** [seedifferently/the-great-web-framework-shootout#12]
we think a picture is worth a thousand words :)

**Comment by seedifferently** [comment]
The README states that graphs can be found on the website. Is this satisfactory to you?

**Comment by irfn** [comment]
sure thanks.
Did you generate these manually. if so how about some scripts/code to generate these. 

## 

Irfan

**Comment by seedifferently** [comment]
I currently just have it tracked in a spreadsheet. Would love any ideas you have for code.

**Comment by irfn** [comment]
if you point me to the apache bench "scripts" or commands, then maybe ill give it a shot :)

**Comment by seedifferently** [comment]
I opened a new ticket for this. Think you can lend a hand to #26?
