### ISSUE TITLE
Playframework

### ISSUE THREAD

**Issue by 0xRoch** [seedifferently/the-great-web-framework-shootout#16]
It would be great to add playframework to the project.

**Comment by kev009** [comment]
Indeed.  I recommend the Play 2.0 RCs.  Make sure you run in production mode.  On the template examples it should ring in at something like 15k/s, and at least 1k/s on DB queries (DB dependent) based on my testing.  I'm never going back to anything else -- amateur hour in comparison.

**Comment by seedifferently** [comment]
Thanks for the suggestion. Can you please comment on Play's popularity? Is it widely used? Are there any big sites built on it?

**Comment by 0xRoch** [comment]
Play is really popular at the moment.
It has been integrated to the typesafe stack recently.
I think it's the most popular scala framework (I not 100% sure tho).
Lift is also very popular and it's used in production by Foursquare.

**Comment by seedifferently** [comment]
Please see #19.
