### ISSUE TITLE
Question about Symfony 2

### ISSUE THREAD

**Issue by xkobal** [seedifferently/the-great-web-framework-shootout#21]
Hello,

In Symfony Framework, the boostrap file is missing.

So it won't show if you have used debug or not in your test.

The test with a debug = true is not a real life test.

So can you show your boostrap for Symfony ?

Best regards.

Xavier

**Comment by seedifferently** [comment]
Xavier, unfortunately I accidentally deleted the bootstrap file before uploading. IIRC, I unset debug = true before testing, but you can run your own tests with the included Symfony code to see for yourself if it performs any better/worse.

Could you please submit a pull request with the bootstrap file you would like to have benchmarked? I can see about running the Symfony test with that on the next update.
