### ISSUE TITLE
why use cakephp 1.3 not 2.0 ?

### ISSUE THREAD

**Issue by meotimdihia** [seedifferently/the-great-web-framework-shootout#25]
If you tested symfony 2.0 compare with  cakephp 1.3 ?
cakephp 2.0 with model lazy loading improved its speed x2 . 

Edit: sorry duplicate with previous topic.

**Comment by meotimdihia** [comment]
Edit: sorry duplicate with previous topic.

**Comment by seedifferently** [comment]
Please see my reply here: https://groups.google.com/forum/?fromgroups#!topic/cake-php/7wXR35T18a0

Thanks,
Seth

**Comment by meotimdihia** [comment]
I think if you want better results , then turn off _debug mode_ for all frameworks. 
_Because_ a production websites isn't in _debug mode_ .
