### ISSUE TITLE
bottle template question

### ISSUE THREAD

**Issue by iurisilvio** [seedifferently/the-great-web-framework-shootout#29]
Why you selected Jinja2 instead of built-in Bottle SimpleTemplate? Of course Jinja2 is powerful, but I guess it is not the default bottle option to a simple app like these benchmarks.

If you agree, I can patch Bottle benchmarks to work with SimpleTemplate.

**Comment by seedifferently** [comment]
Because when I originally tested it, jinja2 was actually faster than the built-in bottle templates for some reason.

Plus, it made the Python tests a bit more similar that way.

**Comment by iurisilvio** [comment]
Makes sense... Thanks for your answer.
