### ISSUE TITLE
Grails?

### ISSUE THREAD

**Issue by joneilloine** [seedifferently/the-great-web-framework-shootout#3]
I'd be very interested in seeing Grails in your results as it's a pretty popular framework on the JVM

**Comment by seedifferently** [comment]
Thanks for the suggestion Jesse. I haven't got any experience with Groovy. Can you please submit a pull request and provide instructions for setting up and running the Gails test?

**Comment by divideby0** [comment]
I've created a sample app using grails.  I'll submit a pull request once I've tested out on EC2 and have numbers to share:

https://github.com/Spantree/the-great-web-framework-shootout/tree/dev/grails

**Comment by divideby0** [comment]
Pull request submitted here: https://github.com/seedifferently/the-great-web-framework-shootout/pull/44
