### ISSUE TITLE
php tests: disable apc.stat*

### ISSUE THREAD

**Issue by doapp-ryanp** [seedifferently/the-great-web-framework-shootout#37]
You may already do this, but for your PHP tests, do you disable file stat'ing in APC?  This will make it so PHP files are not stat'ed on every request.  This is pretty common in production PHP apps.  When putting PHP up against compiled languages (like python) this will give a more apples to apples comparison.

Here are the directives you need to add to your php.ini

```
apc.stat = 0
apc.stat_ctime = 0
```

These directives will require the clearing of the APC optcode cache when you change a PHP file (just restart apache in your case).  Sort of like what the python frameworks do in development mode.  You can find more detailed info about the APC options here: http://php.net/manual/en/apc.configuration.php

**Comment by seedifferently** [comment]
Thanks!
