### ISSUE TITLE
Optimize

### ISSUE THREAD

**Issue by tempire** [seedifferently/the-great-web-framework-shootout#6]
Remove "Ipsum" and you've optimized the transmission time by 55%.

**Comment by seedifferently** [comment]
I'm not sure I'm following you. Could you please explain what you're suggesting? The point of the Ipsum tests is to bog down the frameworks a bit by processing text through the templating system.

**Comment by tempire** [comment]
I'm politely indicating that the tests prove very little, because they assume that web app performance is linearly distributed across the stack.  You could save 10 milliseconds on the template engine, and waste 1 minute on an O(n^5) db select.  You have to test a fully operational web app to get useful metrics.

What really matters in terms of frameworks is developer time, which is fully subjective.

**Comment by seedifferently** [comment]
Right, the disclaimers on the website (http://blog.curiasolutions.com/the-great-web-framework-shootout/) talk about how little real-world value this stuff has. Any developer worth his/her salt knows that all this benchmarking stuff is just for fun, and that real code brings dramatic performance differences with even the slightest changes.

If you have any suggestions on how to make these tests more helpful--while keeping in mind that we're not really shooting for much real-world value--then I'd greatly appreciate your input!

Seth

**Comment by tempire** [comment]
Understood.  My only suggestion is that you put that particular point in
the github readme, because newer devs don't understand this, and the
ensuing useless arguments are rampant.

On Sun, Feb 19, 2012 at 1:19 PM, Seth Davis <
reply@reply.github.com

**Comment by seedifferently** [comment]
Good point. I guess having it on the website probably isn't good enough.

**Comment by seedifferently** [comment]
Closing with 1ba4ac4400eb97955d238baf1a54e36ef7434100
